// Copyright (C) 2010 Talend Inc. - www.talend.com

// This script is run each time a shell is created.
// You can define here closures or variables that will be available
// in each session.
//
ld = { log:display $args } ;
lde = { log:exception-display $args } ;
la = { bundle:list -t 0 $args } ;
ls = { service:list $args } ;
cl = { config:list "(service.pid=$args)" } ;
halt = { system:shutdown -h -f $args } ;
help = { *:help $args | more } ;
man = { help $args } ;
log:list = { log:get ALL } ;
service:get = { $.context getService ($.context getServiceReference $args) };

env = { shell:set $args }
edit = { shell:nano $args }
more = { shell:less $args }

prompt = "[1m${USER}[0m@${APPLICATION}(${SUBSHELL})> "

__load_class = {
  (($.reader class) classLoader) loadClass $1
}

# On 256 colors terminal, add a right prompt
max_colors = ($.jline.terminal getNumericCapability max_colors)
if { %(max_colors >= 256) } {
  __rprompt_formatter = (((__load_class java.text.SimpleDateFormat) getConstructor (__load_class java.lang.String)) newInstance \'$'\u001B\[90m'\'HH:mm:ss)
  __date_class = (__load_class java.util.Date)
  \#rprompt = { $__rprompt_formatter format ($__date_class newInstance) }
}

setopt group
keymap "^[OA" up-line-or-search
keymap "^[OB" down-line-or-search


tesb:start-aux-store = { feature:install tesb-aux } ;
tesb:start-sts = { feature:install tesb-sts } ;
tesb:start-sam = { feature:install tesb-datasource-derby tesb-derby-starter tesb-sam-service-soap tesb-sam-service-rest } ; // (install derby-starter and sam feature)
tesb:start-sam-retrieval-service = { feature:install tesb-datasource-derby tesb-derby-starter tesb-sam-service-rest } ; // (install derby-starter and sam rest feature)
tesb:start-locator = { feature:install tesb-zookeeper-server } ; // (install zookeeper feature)
tesb:start-locator-monitor = { feature:install tesb-locator-monitor } ; // (install locator monitor)
tesb:start-locator-commands = { feature:install tesb-locator-commands } ; // (install locator commands)
tesb:start-all = { tesb:start-sts; tesb:start-sam; tesb:start-locator; tesb:start-aux-store; sleep -s 5; bundle:refresh "Apache CXF JAX-RS Client" } ; // (start all four services)
tesb:stop-aux-store  = {feature:uninstall tesb-aux } ;
tesb:stop-sts = { feature:uninstall tesb-sts } ;
tesb:stop-sam = { feature:uninstall tesb-sam-service-rest tesb-sam-service-soap tesb-datasource-derby tesb-derby-starter } ; // (uninstall derby-starter and sam feature)
tesb:stop-sam-retrieval-service = { feature:uninstall tesb-sam-service-rest tesb-datasource-derby tesb-derby-starter } ; // (uninstall derby-starter and sam rest feature)
tesb:stop-locator = { feature:uninstall tesb-zookeeper-server } ; // (uninstall zookeeper feature)
tesb:stop-locator-monitor = { feature:uninstall tesb-locator-monitor } ; // (uninstall locator monitor)
tesb:stop-locator-commands = { feature:uninstall tesb-locator-commands } ; // (uninstall locator commands)
tesb:stop-all = { tesb:stop-sts; tesb:stop-sam; tesb:stop-locator; tesb:stop-aux-store } ; // (uninstall all four services)
